version: '3'
services:
  mysql:
    image: mysql:8.0-debian
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todolists
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - todo

  todo-app:
    build: .
    container_name: todo-app
    environment:
      DB_HOST: mysql
    networks:
      - todo
    depends_on:
      - mysql
    ports:
      - 8080:8080

networks:
  todo:
    driver: bridge

volumes:
  db_data: